# config/config.yaml
server:
  port: ""

mongo:
  uri: ""
  dbName: ""

jwt:
  secret: ""
  expiration: ""

s3:
  bucket: ""
  region: ""
  accessKeyID: ""
  secretAccessKey: ""

fabric:
  channelName: "meatchannel"
  chaincodeName: "meatcc" 
  orgName: "MeatSupplyOrg"
  userName: "superadmin"
  connectionProfile: "./connection-profile.yaml"
  userCertPath: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/signcerts/cert.pem"
  userKeyDir: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/keystore/"