# config/config.yaml

server:
  port: "8080"

fabric:
  # Thông tin về channel và chaincode
  channelName: "meatchannel"
  chaincodeName: "meatcc"
  
  # Thông tin về tổ chức và danh tính superadmin 
  orgName: "MeatSupplyOrg"
  userName: "superadmin" # Danh tính mà API server dùng để khởi động
  
  # Đường dẫn đến file connection profile (tương đối với thư mục gốc của server)
  connectionProfile: "./connection-profile.yaml"
  
  # === QUAN TRỌNG: CẬP NHẬT CÁC ĐƯỜNG DẪN TUYỆT ĐỐI NÀY ===
  # Đường dẫn đến cert và key của SuperAdmin
  userCertPath: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/signcerts/cert.pem"
  userKeyDir: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/keystore/"