# config/config.yaml
server:
  port: ""

mongo:
  uri: "mongodb+srv://lethanhan20039_db_user:Reiu0PtlQyrbik9K@cluster0.f3pxnpt.mongodb.net/fresh-meat-scm?retryWrites=true&w=majority&appName=Cluster0"
  dbName: "fresh-meat-scm"

jwt:
  secret: ""
  expiration: ""

s3:
  bucket: ""
  region: ""
  accessKeyID: ""
  secretAccessKey: ""
  cloudFrontDomain: ""  # Thêm trường này để lưu tên miền CloudFront

n8n:
  dispatchWebhookURL: ""  # URL webhook để gửi yêu cầu dispatch

fabric:
  channelName: "meatchannel"
  chaincodeName: "meatcc"
  orgName: "MeatSupplyOrg"
  userName: "superadmin"
  connectionProfile: "./connection-profile.yaml"
  userCertPath: "/home/lean1123/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/signcerts/cert.pem"
  userKeyDir: "/home/lean1123/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/keystore/"
