# config/config.yaml
server:
  port: "8080"

fabric:
  channelName: "meatchannel"
  chaincodeName: "meatcc"

  # === THÔNG TIN SUPER ADMIN ===
  superAdmin:
    orgName: "MeatSupplyOrg"
    userName: "superadmin"
    certPath: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/signcerts/cert.pem"
    keyDir: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/keystore/"


  # Thông tin CA để đăng ký user mới
  ca:
    url: "https://localhost:7054"
    caName: "ca.meatsupply.example.com"
    tlsCertPath: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/fabric-ca/meatsupply/ca-cert.pem"

  # Đường dẫn đến file connection profile (tương đối với thư mục server)
  connectionProfile: "./connection-profile.yaml"