# config/config.yaml
server:
  port: "8080"

mongo:
  uri: "mongodb+srv://adminscm:DegAQTucutHGm0nn@admin.wubocek.mongodb.net/fresh-meat-scm?retryWrites=true&w=majority&appName=admin"
  dbName: "fresh-meat-scm"

jwt:
  secret: "your_jwt_secret"
  expiration: "24h"

fabric:
  channelName: "meatchannel"
  chaincodeName: "meatcc" 
  orgName: "MeatSupplyOrg"
  userName: "superadmin"
  connectionProfile: "./connection-profile.yaml"
  userCertPath: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/signcerts/cert.pem"
  userKeyDir: "/home/hhexe/fresh-meat-scm-hyperledger-fabric/network/crypto-config/peerOrganizations/meatsupply.example.com/users/SuperAdmin@meatsupply.example.com/msp/keystore/"